export const CITIES = {
  ALL:'ALL',
  LAHORE:'LAHORE',
  FAISALABAD:'FAISALABAD',
  GUJRANWALA:'GUJRANWALA',
  HYDERABAD:'HYDERABAD',
  SUKKUR:'SUKKUR',
  KARACHI:'KARACHI',
  ISLAMABAD:'ISLAMABAD'
}

export const CATEGORIES ={
  ALL:'ALL',
  FOOD:'FOOD',
  GROCERY:'GROCERY',
  ELECTRICAL:'ELECTRICAL'
}